Repository wixplosives/stylable-intelligence, pull requests merged in 2018-02, with the labels that each got.

#183 State with params
  fixtures/demo/test.css
  fixtures/demo/test.st.css
  fixtures/server-cases/states/with-param/comp-to-import-with-param-and-validators.st.css
  fixtures/server-cases/states/with-param/comp-to-import-with-param.st.css
  fixtures/server-cases/states/with-param/imported-state-param-and-validators-suggestion.st.css
  fixtures/server-cases/states/with-param/imported-state-param-suggestion.st.css
  fixtures/server-cases/states/with-param/imported-state-param.st.css
  fixtures/server-cases/states/with-param/local-state-param-suggestion.st.css
  fixtures/server-cases/states/with-param/local-state-param.st.css
  fixtures/server-cases/states/with-param/state-def-with-param-suggestion.st.css
  package.json
  src/server/completion-providers.ts
  src/server/completion-types.ts
  src/server/provider.ts
  src/server/service.ts
  src/server/types.ts
  test-kit/asserters.ts
  test/server/signatures.spec.ts
  test/server/states.spec.ts
Labels: completions, feature, signature-help

#190 update yarn.lock
  yarn.lock
Labels: infra

#192 Fix missing syntax highlighting on stylable files after refactor
  package.json
  syntaxes/stylable.tmLanguage.json
Labels: bug
