Repository wixplosives/stylable-intelligence, pull requests merged in 2018-03, with the labels that each got.

#194 Upgrade TypeScript@2.7, vscode-language-client/server@4.0.0, webpack@4
  package.json
  src/client/extension.ts
  src/server/server.ts
  src/server/service.ts
  src/server/types.ts
  test/browser-compatible.spec.ts
  test/server/diagnostics.spec.ts
  yarn.lock
Labels: infra

#172 Nadav/pass require hook
  src/server/diagnosis.ts
  src/server/server.ts
  src/server/service.ts
  test/server/diagnostics.spec.ts
Labels: infra

#193 State with param - hinting and completions
  fixtures/demo/test.st.css
  fixtures/server-cases/states/with-param/enum/imported-state-with-enum-middle.st.css
  fixtures/server-cases/states/with-param/enum/imported-state-with-enum-start.st.css
  fixtures/server-cases/states/with-param/enum/state-def-with-param-enum-start.st.css
  fixtures/server-cases/states/with-param/enum/state-with-enum.st.css
  fixtures/server-cases/states/with-param/enum/state-with-param-enum-suggestion.st.css
  fixtures/server-cases/states/with-param/number/local-state-number-validators.st.css
  fixtures/server-cases/states/with-param/number/state-def-with-param-number-max-start.st.css
  fixtures/server-cases/states/with-param/number/state-def-with-param-number-min-start.st.css
  fixtures/server-cases/states/with-param/number/state-def-with-param-number-multiple-start.st.css
  fixtures/server-cases/states/with-param/number/state-def-with-param-number-start.st.css
  fixtures/server-cases/states/with-param/state-def-with-param-end.st.css
  fixtures/server-cases/states/with-param/state-def-with-param-middle.st.css
  fixtures/server-cases/states/with-param/state-def-with-param-start.st.css
  fixtures/server-cases/states/with-param/state-def-with-regex-start.st.css
  fixtures/server-cases/states/with-param/string/local-state-string-validators.st.css
  fixtures/server-cases/states/with-param/string/state-def-with-param-string-contains-start.st.css
  fixtures/server-cases/states/with-param/string/state-def-with-param-string-m-start.st.css
  fixtures/server-cases/states/with-param/string/state-def-with-param-string-regex-start.st.css
  fixtures/server-cases/states/with-param/string/state-def-with-param-string-start.st.css
  fixtures/server-cases/states/with-param/tag/state-def-with-param-tag-start.st.css
  src/server/completion-providers.ts
  src/server/completion-types.ts
  src/server/feature/pseudo-class.ts
  src/server/provider.ts
  src/server/utils/postcss-ast-utils.ts
  test-kit/asserters.ts
  test/server/completion.spec.ts
  test/server/custom-selectors.spec.ts
  test/server/pseudo-elements.spec.ts
  test/server/signatures.spec.ts
  test/server/states.spec.ts
Labels: completions, signature-help

#198 updated readme to reflect extension, added separate doc for dev
  CHANGELOG.md
  README.md
  dev.md
Labels: docs
